CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y

# 左親機だけが左右の状態をまとめてScannerへ送信する。
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="Cornix"
CONFIG_PROSPECTOR_EXPECTED_PERIPHERAL_COUNT=1
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
